name: Publish labs
on:
  push:
    branches:
      - master
    paths:
      - '*/*/README.md'
jobs:
  publish_labs:
    runs-on: ubuntu-20.04
    env:
      USERNAME: ${{ secrets.PP_BOT_USERNAME }}
      PASSWORD: ${{ secrets.PP_BOT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          - fetch-depth: 1

      - name: Archive labs
        run: |
          ./scripts/update-ocw.sh
        uses: docker://pandoc/core:2.9
